### ISSUE TITLE
Open edit event screen from URL

### ISSUE THREAD

**Issue by larshelge** [dhis2/event-capture-app#10]
Add support for opening the edit event screen for a specific event from URL. The URL should include the event identifier.

This will enable integration from third-party apps, where the app can point directly to an existing event.

**Comment by abyot** [comment]
I also think for the URL to contain orgUnit... we can then make sure the user has access to the orgunit and program the event belongs ...

**Comment by larshelge** [comment]
I think that has to be checked in any case on the server side in order to be secure. We can get the org unit from the event. And since it must be checked on the server side, it might not be a point in specifying it in the URL.

**Comment by abyot** [comment]
of course, server side needs to ensure access control is respected. having orgunit will help address the question of what happens next... what if the user wants to add another event,... we need to be in a position to continue the "normal event capture UI and workflow"... we can of course pick the orgunit from the event and select the same in the tree...

**Comment by jijukjose** [comment]
The feature is implemented and deployed to the dev server.
Sample link : https://play.dhis2.org/dev/dhis-web-event-capture/index.html#/?ou=DiszpKrYNg8&event=xmqrawVQZez
