### ISSUE TITLE
i18n Issues

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/event-capture-app#11]
Username: cjl
Current URL: https://translate.dhis2.org/en/event-capture-app/translate/
IP address: 163.252.254.203
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

Unit: https://translate.dhis2.org/en/event-capture-app/translate/i18n/en.po#unit=756265

Source: You are currently offline. But program is configured to be skipped during offline.

Current translation: You are currently offline. But program is configured to be skipped during offline.

Your question or comment:

What does this even mean????

Username: cjl
Current URL: https://translate.dhis2.org/en/event-capture-app/translate/
IP address: 163.252.254.203
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

Unit: https://translate.dhis2.org/en/event-capture-app/translate/i18n/en.po#unit=756243

Source: Value must be integer

Current translation: Value must be integer

Your question or comment:

extra ending whitespace

Username: cjl
Current URL: https://translate.dhis2.org/en/event-capture-app/translate/
IP address: 163.252.254.203
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

Unit: https://translate.dhis2.org/en/event-capture-app/translate/i18n/en.po#unit=756233

Source: About DHIS 2

Current translation: About DHIS 2

Your question or comment:

extra ending whitespace

Username: cjl
Current URL: https://translate.dhis2.org/en/event-capture-app/translate/
IP address: 163.252.254.203
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

Unit: https://translate.dhis2.org/en/event-capture-app/translate/i18n/en.po#unit=756218

Source: Get from map

Current translation: Get from map

Your question or comment:

extra ending whitespace

Username: cjl
Current URL: https://translate.dhis2.org/en/event-capture-app/translate/
IP address: 163.252.254.203
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

Unit: https://translate.dhis2.org/en/event-capture-app/translate/i18n/en.po#unit=756176

Source: No of rows per page

Current translation: Number of rows per page

Your question or comment:

No > Number

Username: cjl
Current URL: https://translate.dhis2.org/en/event-capture-app/translate/
IP address: 163.252.254.203
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

Unit: https://translate.dhis2.org/en/event-capture-app/translate/i18n/en.po#unit=756172

Source: Event uid

Current translation: Event UID

Your question or comment:

Capitalize UID

**Comment by abyot** [comment]
@jason-p-pickering I am closing this one

**Comment by jason-p-pickering** [comment]
Did you fix it?

**Comment by abyot** [comment]
not sure what to fix

**Comment by jason-p-pickering** [comment]
Does not look like it

https://github.com/dhis2/event-capture-app/blob/master/i18n/i18n_app.properties#L177

This is not really even grammatically correct, and the user has pointed out issues in the English messages which need to be rectified.
