### ISSUE TITLE
Buttons vertical padding, on resize

### ISSUE THREAD

**Issue by VladislavAlfredov** [dhis2/event-capture-app#17]
Related to the fix to issue Buttons misplaced (2.24)#3.

When rearranging the buttons upon window resize, the vertical padding between the buttons is 0.
Maybe it should be set to the same value as the horizontal padding.

![buttons_placement_screenshot_2016-10-05_12-19-41](https://cloud.githubusercontent.com/assets/15628235/19109634/8932948c-8af6-11e6-9c33-8926cf352e23.png)

**Comment by abyot** [comment]
Thanks,  this is now fixed.
