### ISSUE TITLE
Cannot change program after selecting one

### ISSUE THREAD

**Issue by larshelge** [dhis2/event-capture-app#6]
In event capture, when you select a program from the program list, you cannot change it to another program.

Applies to snapshot and 2.24.

![reg](https://cloud.githubusercontent.com/assets/908206/17342911/9a421180-58fb-11e6-87f5-dcb66d781aa8.png)

**Comment by abyot** [comment]
This was an intended behavior we introduced some time back. 

It is not possible to change program once a register button is clicked. One needs to click cancel (register form) and then re-select program.
