### ISSUE TITLE
Files are appearing on edit event even when there is no file

### ISSUE THREAD

**Issue by larshelge** [dhis2/event-capture-app#7]
Files are appearing on edit event screen even when there is no file.

Steps
---
- Create an event A where you upload a file for a data element.
- Create another event B where you leave the the file data element field empty.
- Open the edit screen for event B.
- The file from event A is now visible in the input field, even if there should be no file there. When clicking on it, file is not found.

**Comment by abyot** [comment]
@larshelge this is now fixed.
