### ISSUE TITLE
File upload not working in edit event screen

### ISSUE THREAD

**Issue by larshelge** [dhis2/event-capture-app#8]
File upload is not working in the edit event screen. Getting file not found.

Steps
--
- Create an event where you leave a data element of type file empty (do not upload a file) and save it.
- From the list of events, click edit event for the newly created event.
- Upload a file.
- Save the event.
- From the list of events, click edit event.
- Click on the file link in the form.
- Leads to Not found.

**Comment by grelland** [comment]
Was due to server side issue (and double-save of event data values). Fixed in core and backported to >= 2.23
